### ISSUE TITLE
Android App freezing and slow when using NetGuard 

### ISSUE THREAD

**Issue by zeroflaw** [ava-labs/core-mobile#1680]
There are multiple reports in the Google Play store of the Core App becoming slow and unresponsive. They may all be using NetGuard or some other network related IP filtering. I would like to work with you to track down the cause of this issue and fix it.

This issue only occurs when using NetGuard with "Filter traffic" turned on (NetGuard -> Settings -> Advanced options)
This issue only occurs once you have staked or have Avalanche (P-Chain) as a (Favourite / Managed network)

With Filter traffic turned on the the C-Chain, loads and works successfully. 
With Filter traffic turned on the P-Chain, balances and activity fail to load.

There seems to be some sort of incompatibility with NetGuard and balance requests for the Avalanche (P-Chain). I have looked through the code, but I can't find anything obvious, or how the C-Chain and P-Chain balances / activity loading differ.

The only thing I have noticed is the Network RPC URL is "https://api.avax.network" not fully qualified to "https://api.avax.network/ext/bc/P" maybe some auto redirect is causing a problem? 

You can download the NetGuard APK here: https://github.com/M66B/NetGuard 

You don't even need to restart the Core-App, you can toggle the "Filter traffic" button in NetGuard and the balances and activity disappear in the Core-App. Turn it off and everything reappears. 

I'm not setup for Android development, so I am unable to read the logs, but my best guess is a malformed packet is being swallowed by https://github.com/M66B/NetGuard/blob/f07ec3b6ed5d27215dc59f30ba0305e0accd4e2b/app/src/main/jni/netguard/ip.c

**Comment by atn4z7** [comment]
Hi @zeroflaw, thanks for reporting. We actually ran into a somewhat similar issue with the P-Chain and found out that all the requests get rate limited super easily on Android. We were able to fix it and released a new version 3 days ago. Could you try again with the latest version/code?

**Comment by zeroflaw** [comment]
Can confirm, able to run with NetGuard enabled, the issue has been fixed.
